import navJson from '@/data/nav.json';

// Slim per-page nav data for CLIENT components. Generated by scripts/gen_nav.js.
// Deliberately excludes body_html / schemas / faqs / toc / outbound_links so the
// full content.json is never shipped to the browser bundle.
export interface NavPage {
  path: string;
  title: string;
  layer: string;
  cluster: string;
  primary_kw: string;
  funnel: string;
  meta_description: string;
}

const NAV_PAGES = navJson as NavPage[];
const BY_PATH: Record<string, NavPage> = Object.fromEntries(
  NAV_PAGES.map(p => [p.path, p])
);

export function getAllPaths(): string[] {
  return NAV_PAGES.map(p => p.path);
}

export function getPage(path: string): NavPage | null {
  // normalize: ensure leading slash, ensure trailing slash (matches lib/content)
  let p = path.startsWith('/') ? path : '/' + path;
  if (!p.endsWith('/')) p += '/';
  return BY_PATH[p] || null;
}

export function getByLayer(layer: string): NavPage[] {
  return NAV_PAGES.filter(p => p.layer === layer);
}

export function getByCluster(cluster: string): NavPage[] {
  return NAV_PAGES.filter(p => p.cluster === cluster);
}

// Static nav menu structure (unchanged from lib/content).
export const NAV = {
  services: [
    { path: '/casino-app-development/', label: 'Casino App Development' },
    { path: '/slot-game-development/', label: 'Slot Game Development' },
    { path: '/sports-exchange-development/', label: 'Sports Exchange' },
    { path: '/igaming-api-integration/', label: 'API Integration' },
    { path: '/igaming-ui-ux-design/', label: 'UI/UX Design' },
    { path: '/igaming-maintenance-debugging/', label: 'Maintenance & Debugging' },
    { path: '/igaming-mvp-consultancy/', label: 'MVP Consultancy' },
  ],
  solutions: [
    { path: '/solutions/white-label-casino-solutions/', label: 'White-Label Casino' },
    { path: '/solutions/crypto-casino-solutions/', label: 'Crypto Casino' },
    { path: '/solutions/real-money-gaming-solutions/', label: 'Real Money Gaming' },
    { path: '/solutions/custom-igaming-software-solutions/', label: 'Custom Software' },
    { path: '/solutions/enterprise-igaming-platforms/', label: 'Enterprise Platforms' },
    { path: '/solutions/igaming-startup-solutions/', label: 'Startup Solutions' },
  ],
  industries: [
    { path: '/industries/online-casino-operators/', label: 'Casino Operators' },
    { path: '/industries/sports-betting-operators/', label: 'Sports Betting' },
    { path: '/industries/igaming-startups/', label: 'iGaming Startups' },
    { path: '/industries/crypto-gambling-platforms/', label: 'Crypto Gambling' },
    { path: '/industries/game-aggregators/', label: 'Game Aggregators' },
    { path: '/industries/investors-enterprises/', label: 'Investors & Enterprises' },
  ],
  geo: [
    { path: '/igaming-development-company-usa/', label: 'USA' },
    { path: '/igaming-development-company-uk/', label: 'UK' },
    { path: '/igaming-development-company-canada/', label: 'Canada' },
    { path: '/igaming-development-company-australia/', label: 'Australia' },
    { path: '/igaming-development-company-malta/', label: 'Malta' },
    { path: '/igaming-development-company-germany/', label: 'Germany' },
    { path: '/igaming-development-company-india/', label: 'India' },
    { path: '/igaming-development-company-uae/', label: 'UAE' },
  ],
};
